// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: one

#ifndef UI_SCREENTWO_H
#define UI_SCREENTWO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screentwo
extern void ui_screentwo_screen_init(void);
extern void ui_screentwo_screen_destroy(void);
extern lv_obj_t * ui_screentwo;
extern lv_obj_t * ui_arc2;
extern lv_obj_t * ui_number2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

