// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: one

#include "ui.h"

lv_obj_t * ui_screenone = NULL;
lv_obj_t * ui_arc1 = NULL;
lv_obj_t * ui_number1 = NULL;
// event funtions

// build funtions

void ui_screenone_screen_init(void)
{
    ui_screenone = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arc1 = lv_arc_create(ui_screenone);
    lv_obj_set_width(ui_arc1, 150);
    lv_obj_set_height(ui_arc1, 150);
    lv_obj_set_x(ui_arc1, -1);
    lv_obj_set_y(ui_arc1, 78);
    lv_obj_set_align(ui_arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arc1, 25);
    lv_arc_set_bg_angles(ui_arc1, 120, 119);
    lv_arc_set_rotation(ui_arc1, -30);
    lv_obj_set_style_arc_color(ui_arc1, lv_color_hex(0x92E49C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc1, lv_color_hex(0xDF5269), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc1, lv_color_hex(0xDE506A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_number1 = lv_label_create(ui_screenone);
    lv_obj_set_width(ui_number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_number1, -1);
    lv_obj_set_y(ui_number1, 80);
    lv_obj_set_align(ui_number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1, "00");
    lv_obj_set_style_text_font(ui_number1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_screenone_screen_destroy(void)
{
    if(ui_screenone) lv_obj_del(ui_screenone);

    // NULL screen variables
    ui_screenone = NULL;
    ui_arc1 = NULL;
    ui_number1 = NULL;

}
