// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: one

#include "ui.h"

void ui_comp_bientro_create_hook(lv_obj_t * comp)
{
}

void ui_comp_text1_create_hook(lv_obj_t * comp)
{
}
