// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: one

#ifndef UI_SCREENONE_H
#define UI_SCREENONE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenone
extern void ui_screenone_screen_init(void);
extern void ui_screenone_screen_destroy(void);
extern lv_obj_t * ui_screenone;
extern lv_obj_t * ui_arc1;
extern lv_obj_t * ui_number1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

