// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: one

#include "ui.h"

lv_obj_t * ui_screentwo = NULL;
lv_obj_t * ui_arc2 = NULL;
lv_obj_t * ui_number2 = NULL;
// event funtions

// build funtions

void ui_screentwo_screen_init(void)
{
    ui_screentwo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screentwo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arc2 = lv_arc_create(ui_screentwo);
    lv_obj_set_width(ui_arc2, 150);
    lv_obj_set_height(ui_arc2, 150);
    lv_obj_set_x(ui_arc2, -1);
    lv_obj_set_y(ui_arc2, -77);
    lv_obj_set_align(ui_arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arc2, 25);
    lv_arc_set_bg_angles(ui_arc2, 120, 119);
    lv_arc_set_rotation(ui_arc2, -30);
    lv_obj_set_style_arc_color(ui_arc2, lv_color_hex(0x92E49C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc2, lv_color_hex(0xDF5269), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc2, lv_color_hex(0xDE506A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_number2 = lv_label_create(ui_screentwo);
    lv_obj_set_width(ui_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_number2, 0);
    lv_obj_set_y(ui_number2, -76);
    lv_obj_set_align(ui_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2, "00");
    lv_obj_set_style_text_font(ui_number2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_screentwo_screen_destroy(void)
{
    if(ui_screentwo) lv_obj_del(ui_screentwo);

    // NULL screen variables
    ui_screentwo = NULL;
    ui_arc2 = NULL;
    ui_number2 = NULL;

}
