// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_UV

#include "ui.h"

lv_obj_t * ui_Screenload = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_load = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_loadtrangthai = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Screenload_screen_init(void)
{
    ui_Screenload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screenload);
    lv_img_set_src(ui_Image1, &ui_img_bg1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 883
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 523
    lv_obj_set_x(ui_Image1, -3);
    lv_obj_set_y(ui_Image1, 15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    ui_Container2 = lv_obj_create(ui_Screenload);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 248);
    lv_obj_set_height(ui_Container2, 173);
    lv_obj_set_x(ui_Container2, 6);
    lv_obj_set_y(ui_Container2, -2);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_load = lv_spinner_create(ui_Container2, 1000, 90);
    lv_obj_set_width(ui_load, 56);
    lv_obj_set_height(ui_load, 40);
    lv_obj_set_x(ui_load, -2);
    lv_obj_set_y(ui_load, -6);
    lv_obj_set_align(ui_load, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_load, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_load, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_load, lv_color_hex(0x53DB49), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_load, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_load, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -4);
    lv_obj_set_y(ui_Label2, 27);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Wait a minute, the program is being set up...");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadtrangthai = lv_bar_create(ui_Screenload);
    lv_bar_set_value(ui_loadtrangthai, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_loadtrangthai, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_loadtrangthai, 295);
    lv_obj_set_height(ui_loadtrangthai, 10);
    lv_obj_set_x(ui_loadtrangthai, 2);
    lv_obj_set_y(ui_loadtrangthai, 65);
    lv_obj_set_align(ui_loadtrangthai, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_loadtrangthai, lv_color_hex(0x52DA4A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadtrangthai, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screenload);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, -84);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "\nWelcome ");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screenload);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, -49);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "UV AI");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screenload_screen_destroy(void)
{
    if(ui_Screenload) lv_obj_del(ui_Screenload);

    // NULL screen variables
    ui_Screenload = NULL;
    ui_Image1 = NULL;
    ui_Container2 = NULL;
    ui_load = NULL;
    ui_Label2 = NULL;
    ui_loadtrangthai = NULL;
    ui_Label3 = NULL;
    ui_Label1 = NULL;

}
