// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_UV

#include "ui.h"

lv_obj_t * uic_Screen;
lv_obj_t * ui_Screen = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_ContainerUVnext = NULL;
lv_obj_t * ui_UVNumbernext = NULL;
lv_obj_t * ui_UVnexthour = NULL;
lv_obj_t * ui_UVtext1 = NULL;
lv_obj_t * ui_ArcUv1 = NULL;
lv_obj_t * ui_ContainerUVnow = NULL;
lv_obj_t * ui_UVNumber = NULL;
lv_obj_t * ui_UVtext = NULL;
lv_obj_t * ui_ArcUv = NULL;
lv_obj_t * ui_ImageUV = NULL;
lv_obj_t * ui_UVnow = NULL;
lv_obj_t * ui_Containertemp = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_TempNumber = NULL;
lv_obj_t * ui_donvitemp1 = NULL;
lv_obj_t * ui_Donvitempc = NULL;
lv_obj_t * ui_phantrampin = NULL;
lv_obj_t * ui_imagepin = NULL;
lv_obj_t * ui_Panelcanhbao = NULL;
lv_obj_t * ui_canhbao = NULL;
lv_obj_t * ui_Containerhum = NULL;
lv_obj_t * ui_ArcHum = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Humptext = NULL;
lv_obj_t * ui_HumNumber = NULL;
// event funtions

// build funtions

void ui_Screen_screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Screen);
    lv_img_set_src(ui_Image23, &ui_img_bg1_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 883
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 523
    lv_obj_set_x(ui_Image23, -7);
    lv_obj_set_y(ui_Image23, 11);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image23, 100);

    ui_ContainerUVnext = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_ContainerUVnext);
    lv_obj_set_width(ui_ContainerUVnext, 250);
    lv_obj_set_height(ui_ContainerUVnext, 159);
    lv_obj_set_x(ui_ContainerUVnext, -16);
    lv_obj_set_y(ui_ContainerUVnext, -4);
    lv_obj_set_align(ui_ContainerUVnext, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerUVnext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UVNumbernext = lv_label_create(ui_ContainerUVnext);
    lv_obj_set_width(ui_UVNumbernext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVNumbernext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVNumbernext, 73);
    lv_obj_set_y(ui_UVNumbernext, -20);
    lv_obj_set_align(ui_UVNumbernext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVNumbernext, "00");
    lv_obj_set_style_text_font(ui_UVNumbernext, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVnexthour = lv_label_create(ui_ContainerUVnext);
    lv_obj_set_width(ui_UVnexthour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVnexthour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVnexthour, 72);
    lv_obj_set_y(ui_UVnexthour, 21);
    lv_obj_set_align(ui_UVnexthour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVnexthour, "next hour");
    lv_obj_set_style_text_font(ui_UVnexthour, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVtext1 = lv_label_create(ui_ContainerUVnext);
    lv_obj_set_width(ui_UVtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVtext1, 72);
    lv_obj_set_y(ui_UVtext1, 8);
    lv_obj_set_align(ui_UVtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVtext1, "UV");
    lv_obj_set_style_text_font(ui_UVtext1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUv1 = lv_arc_create(ui_ContainerUVnext);
    lv_obj_set_width(ui_ArcUv1, 99);
    lv_obj_set_height(ui_ArcUv1, 100);
    lv_obj_set_x(ui_ArcUv1, 73);
    lv_obj_set_y(ui_ArcUv1, -22);
    lv_obj_set_align(ui_ArcUv1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcUv1, 50);
    lv_arc_set_bg_angles(ui_ArcUv1, 120, 0);

    ui_ContainerUVnow = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_ContainerUVnow);
    lv_obj_set_width(ui_ContainerUVnow, 266);
    lv_obj_set_height(ui_ContainerUVnow, 181);
    lv_obj_set_x(ui_ContainerUVnow, 15);
    lv_obj_set_y(ui_ContainerUVnow, -3);
    lv_obj_set_align(ui_ContainerUVnow, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerUVnow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UVNumber = lv_label_create(ui_ContainerUVnow);
    lv_obj_set_width(ui_UVNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVNumber, -70);
    lv_obj_set_y(ui_UVNumber, -20);
    lv_obj_set_align(ui_UVNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVNumber, "00");
    lv_obj_set_style_text_font(ui_UVNumber, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVtext = lv_label_create(ui_ContainerUVnow);
    lv_obj_set_width(ui_UVtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVtext, -70);
    lv_obj_set_y(ui_UVtext, 13);
    lv_obj_set_align(ui_UVtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVtext, "UV");
    lv_obj_set_style_text_font(ui_UVtext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUv = lv_arc_create(ui_ContainerUVnow);
    lv_obj_set_width(ui_ArcUv, 114);
    lv_obj_set_height(ui_ArcUv, 116);
    lv_obj_set_x(ui_ArcUv, -71);
    lv_obj_set_y(ui_ArcUv, -20);
    lv_obj_set_align(ui_ArcUv, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcUv, 50);
    lv_arc_set_bg_angles(ui_ArcUv, 190, 60);

    ui_ImageUV = lv_img_create(ui_ContainerUVnow);
    lv_img_set_src(ui_ImageUV, &ui_img_1019162763);
    lv_obj_set_width(ui_ImageUV, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageUV, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageUV, -32);
    lv_obj_set_y(ui_ImageUV, -66);
    lv_obj_set_align(ui_ImageUV, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageUV, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageUV, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageUV, 200);

    ui_UVnow = lv_label_create(ui_ContainerUVnow);
    lv_obj_set_width(ui_UVnow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVnow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVnow, -70);
    lv_obj_set_y(ui_UVnow, 26);
    lv_obj_set_align(ui_UVnow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVnow, "now");
    lv_obj_set_style_text_font(ui_UVnow, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containertemp = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_Containertemp);
    lv_obj_set_width(ui_Containertemp, 318);
    lv_obj_set_height(ui_Containertemp, 202);
    lv_obj_set_x(ui_Containertemp, 15);
    lv_obj_set_y(ui_Containertemp, -55);
    lv_obj_set_align(ui_Containertemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containertemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Containertemp);
    lv_img_set_src(ui_Image14, &ui_img_sun_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image14, -146);
    lv_obj_set_y(ui_Image14, 70);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image14, 200);

    ui_ArcTemp = lv_arc_create(ui_Containertemp);
    lv_obj_set_width(ui_ArcTemp, 45);
    lv_obj_set_height(ui_ArcTemp, 45);
    lv_obj_set_x(ui_ArcTemp, -127);
    lv_obj_set_y(ui_ArcTemp, 55);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcTemp, 50);
    lv_arc_set_bg_angles(ui_ArcTemp, 90, 89);
    lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcTemp, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xECEF50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xECEF50), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempNumber = lv_label_create(ui_Containertemp);
    lv_obj_set_width(ui_TempNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempNumber, -127);
    lv_obj_set_y(ui_TempNumber, 56);
    lv_obj_set_align(ui_TempNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempNumber, "00");
    lv_obj_set_style_text_font(ui_TempNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_donvitemp1 = lv_label_create(ui_Containertemp);
    lv_obj_set_width(ui_donvitemp1, 8);
    lv_obj_set_height(ui_donvitemp1, 8);
    lv_obj_set_x(ui_donvitemp1, -115);
    lv_obj_set_y(ui_donvitemp1, 31);
    lv_obj_set_align(ui_donvitemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_donvitemp1, "O");
    lv_obj_set_style_text_font(ui_donvitemp1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Donvitempc = lv_label_create(ui_Containertemp);
    lv_obj_set_width(ui_Donvitempc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Donvitempc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Donvitempc, -109);
    lv_obj_set_y(ui_Donvitempc, 39);
    lv_obj_set_align(ui_Donvitempc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Donvitempc, "C");
    lv_obj_set_style_text_font(ui_Donvitempc, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_phantrampin = lv_bar_create(ui_Screen);
    lv_bar_set_value(ui_phantrampin, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_phantrampin, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_phantrampin, 25);
    lv_obj_set_height(ui_phantrampin, 16);
    lv_obj_set_x(ui_phantrampin, 133);
    lv_obj_set_y(ui_phantrampin, -75);
    lv_obj_set_align(ui_phantrampin, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_phantrampin, lv_color_hex(0xF0FF4F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_phantrampin, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_imagepin = lv_img_create(ui_Screen);
    lv_img_set_src(ui_imagepin, &ui_img_battery_png);
    lv_obj_set_width(ui_imagepin, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imagepin, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imagepin, 135);
    lv_obj_set_y(ui_imagepin, -75);
    lv_obj_set_align(ui_imagepin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagepin, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagepin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panelcanhbao = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_Panelcanhbao, 286);
    lv_obj_set_height(ui_Panelcanhbao, 50);
    lv_obj_set_x(ui_Panelcanhbao, 0);
    lv_obj_set_y(ui_Panelcanhbao, 60);
    lv_obj_set_align(ui_Panelcanhbao, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelcanhbao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_canhbao = lv_label_create(ui_Panelcanhbao);
    lv_obj_set_width(ui_canhbao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_canhbao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_canhbao, 1);
    lv_obj_set_y(ui_canhbao, 0);
    lv_obj_set_align(ui_canhbao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_canhbao, "High - SPF 50+++\nUV in the next hour: ");
    lv_obj_set_style_text_color(ui_canhbao, lv_color_hex(0xF4B026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_canhbao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_canhbao, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containerhum = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_Containerhum);
    lv_obj_set_width(ui_Containerhum, 315);
    lv_obj_set_height(ui_Containerhum, 167);
    lv_obj_set_x(ui_Containerhum, -16);
    lv_obj_set_y(ui_Containerhum, -56);
    lv_obj_set_align(ui_Containerhum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containerhum, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcHum = lv_arc_create(ui_Containerhum);
    lv_obj_set_width(ui_ArcHum, 45);
    lv_obj_set_height(ui_ArcHum, 45);
    lv_obj_set_x(ui_ArcHum, 130);
    lv_obj_set_y(ui_ArcHum, 55);
    lv_obj_set_align(ui_ArcHum, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcHum, 50);
    lv_arc_set_bg_angles(ui_ArcHum, 90, 89);
    lv_obj_set_style_arc_width(ui_ArcHum, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHum, lv_color_hex(0x2B38AE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHum, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHum, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHum, lv_color_hex(0x2B38AE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHum, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcHum, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcHum, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcHum, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcHum, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_Containerhum);
    lv_img_set_src(ui_Image15, &ui_img_hum_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image15, 114);
    lv_obj_set_y(ui_Image15, 70);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image15, 150);

    ui_Humptext = lv_label_create(ui_Containerhum);
    lv_obj_set_width(ui_Humptext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humptext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humptext, 146);
    lv_obj_set_y(ui_Humptext, 38);
    lv_obj_set_align(ui_Humptext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humptext, "%");
    lv_obj_set_style_text_font(ui_Humptext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumNumber = lv_label_create(ui_Containerhum);
    lv_obj_set_width(ui_HumNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumNumber, 130);
    lv_obj_set_y(ui_HumNumber, 56);
    lv_obj_set_align(ui_HumNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumNumber, "00");
    lv_obj_set_style_text_font(ui_HumNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen = ui_Screen;

}

void ui_Screen_screen_destroy(void)
{
    if(ui_Screen) lv_obj_del(ui_Screen);

    // NULL screen variables
    uic_Screen = NULL;
    ui_Screen = NULL;
    ui_Image23 = NULL;
    ui_ContainerUVnext = NULL;
    ui_UVNumbernext = NULL;
    ui_UVnexthour = NULL;
    ui_UVtext1 = NULL;
    ui_ArcUv1 = NULL;
    ui_ContainerUVnow = NULL;
    ui_UVNumber = NULL;
    ui_UVtext = NULL;
    ui_ArcUv = NULL;
    ui_ImageUV = NULL;
    ui_UVnow = NULL;
    ui_Containertemp = NULL;
    ui_Image14 = NULL;
    ui_ArcTemp = NULL;
    ui_TempNumber = NULL;
    ui_donvitemp1 = NULL;
    ui_Donvitempc = NULL;
    ui_phantrampin = NULL;
    ui_imagepin = NULL;
    ui_Panelcanhbao = NULL;
    ui_canhbao = NULL;
    ui_Containerhum = NULL;
    ui_ArcHum = NULL;
    ui_Image15 = NULL;
    ui_Humptext = NULL;
    ui_HumNumber = NULL;

}
