// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_UV

#ifndef UI_SCREENLOAD_H
#define UI_SCREENLOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screenload
extern void ui_Screenload_screen_init(void);
extern void ui_Screenload_screen_destroy(void);
extern lv_obj_t * ui_Screenload;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_load;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_loadtrangthai;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

