// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_UV

#ifndef UI_SCREEN_H
#define UI_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen
extern void ui_Screen_screen_init(void);
extern void ui_Screen_screen_destroy(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_ContainerUVnext;
extern lv_obj_t * ui_UVNumbernext;
extern lv_obj_t * ui_UVnexthour;
extern lv_obj_t * ui_UVtext1;
extern lv_obj_t * ui_ArcUv1;
extern lv_obj_t * ui_ContainerUVnow;
extern lv_obj_t * ui_UVNumber;
extern lv_obj_t * ui_UVtext;
extern lv_obj_t * ui_ArcUv;
extern lv_obj_t * ui_ImageUV;
extern lv_obj_t * ui_UVnow;
extern lv_obj_t * ui_Containertemp;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_TempNumber;
extern lv_obj_t * ui_donvitemp1;
extern lv_obj_t * ui_Donvitempc;
extern lv_obj_t * ui_phantrampin;
extern lv_obj_t * ui_imagepin;
extern lv_obj_t * ui_Panelcanhbao;
extern lv_obj_t * ui_canhbao;
extern lv_obj_t * ui_Containerhum;
extern lv_obj_t * ui_ArcHum;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Humptext;
extern lv_obj_t * ui_HumNumber;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

